
/**
 * NOTE: This file is auto-generated by Corract!
 * If you modify it, your changes will be lost on the next dev / build.
 * 
 * - App Entry Point -
 * 
 * This is the entry point for a Preact application.
 * 
 * The current plan is to allow drivers to be set up to use this framework
 * with different ui libraries, routing libraries, state management, etc.
 */

import { render } from "preact";
import Router from "preact-router";
import Page0 from "./pages/";
import Page1 from "./pages/profile";

function App() {
  return (
    <Router>
      <Page0 path="/" />
      <Page1 path="/profile" />
    </Router>
  );
}

render(<App />, document.getElementById("app")!);
