/**
 * NOTE: This file is auto-generated by Corract!
 * If you modify it, your changes will be lost on the next dev / build.
 *
 * - App Entry Point -
 *
 * This is the entry point for a Preact application.
 *
 * The current plan is to allow drivers to be set up to use this framework
 * with different ui libraries, routing libraries, state management, etc.
 */
/* eslint-disable @stylistic/jsx-pascal-case */


import type { ClientProps } from 'corract'
import { render } from 'preact'
import { useState } from 'preact/hooks'
import { Router, Route } from 'preact-router'
import { ServerStateProvider } from 'corract'

import { pages } from './app-def'

import Page_ from './pages/'
import Page_profile from './pages/profile'
import Page_profile_demo from './pages/profile/demo'
import Page_profile___x__id from './pages/profile/[id]'
import Page_tasks from './pages/tasks'
import Page_docs from './pages/docs'
import Page_docs_app_def from './pages/docs/app/def'
import Page_docs_app_client from './pages/docs/app/client'
import Page_docs_app_start from './pages/docs/app/start'
import Page_docs_app_style from './pages/docs/app/style'
import Page_docs_src_pages from './pages/docs/src/pages'
import Page_docs_src_layouts from './pages/docs/src/layouts'
import Page_docs_src_middleware from './pages/docs/src/middleware'
import Page_docs_src_components from './pages/docs/src/components'
import Page_docs_src_assets from './pages/docs/src/assets'
import Page_docs_src_styles from './pages/docs/src/styles'
import Page_docs_tools_hooks from './pages/docs/tools/hooks'
import Page_docs_tools_components from './pages/docs/tools/components'
import Page_docs_third__d__party_preact from './pages/docs/third-party/preact'
import Page_docs_third__d__party_express from './pages/docs/third-party/express'
import Page_docs_third__d__party_vite from './pages/docs/third-party/vite'
import Page_docs_third__d__party_typescript from './pages/docs/third-party/typescript'
import Page_docs_third__d__party_eslint from './pages/docs/third-party/eslint'
import Layout_Navbar from './layouts/Navbar'
import Layout_Profile from './layouts/Profile'
import Layout_Docs from './layouts/Docs'

let ssrPagePath: string | undefined
const pathHandler = <T extends keyof typeof pages>(pagePath: T) => {
  if (ssrPagePath) {
    if (ssrPagePath === pagePath) {
      return '/' as typeof pagePath
    } else {
      return '/404' as unknown as typeof pagePath
    }
  } else {
    return pagePath
  }
}

export function Client(props?: ClientProps) {
  ssrPagePath = props?.ssrPagePath as string | undefined
  const [currentPath, setCurrentPath] = useState<string | undefined>(ssrPagePath)

  return (
    <ServerStateProvider
      currentPath={currentPath}
      middlewareData={props?.middlewareData}
    >
      <Router onChange={(e) => setCurrentPath(e.url)}>
        <Route pages={pages} page={pages['/']} path={pathHandler('/')} component={_Navbar}/>
        <Route pages={pages} page={pages['/profile']} path={pathHandler('/profile')} component={_Navbar}/>
        <Route pages={pages} page={pages['/profile/demo']} path={pathHandler('/profile/demo')} component={Page_profile_demo}/>
        <Route pages={pages} page={pages['/profile/:id']} path={pathHandler('/profile/:id')} component={_Profile}/>
        <Route pages={pages} page={pages['/tasks']} path={pathHandler('/tasks')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs']} path={pathHandler('/docs')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/app/def']} path={pathHandler('/docs/app/def')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/app/client']} path={pathHandler('/docs/app/client')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/app/start']} path={pathHandler('/docs/app/start')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/app/style']} path={pathHandler('/docs/app/style')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/src/pages']} path={pathHandler('/docs/src/pages')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/src/layouts']} path={pathHandler('/docs/src/layouts')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/src/middleware']} path={pathHandler('/docs/src/middleware')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/src/components']} path={pathHandler('/docs/src/components')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/src/assets']} path={pathHandler('/docs/src/assets')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/src/styles']} path={pathHandler('/docs/src/styles')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/tools/hooks']} path={pathHandler('/docs/tools/hooks')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/tools/components']} path={pathHandler('/docs/tools/components')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/third-party/preact']} path={pathHandler('/docs/third-party/preact')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/third-party/express']} path={pathHandler('/docs/third-party/express')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/third-party/vite']} path={pathHandler('/docs/third-party/vite')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/third-party/typescript']} path={pathHandler('/docs/third-party/typescript')} component={_Navbar}/>
        <Route pages={pages} page={pages['/docs/third-party/eslint']} path={pathHandler('/docs/third-party/eslint')} component={_Navbar}/>
      </Router>
    </ServerStateProvider>
  )
}

function _Navbar() {
  return (
    <Layout_Navbar>
      <Router>
        <Route pages={pages} page={pages['/']} path={pathHandler('/')} component={Page_}/>
        <Route pages={pages} page={pages['/profile']} path={pathHandler('/profile')} component={_Navbar_Profile}/>
        <Route pages={pages} page={pages['/tasks']} path={pathHandler('/tasks')} component={Page_tasks}/>
        <Route pages={pages} page={pages['/docs']} path={pathHandler('/docs')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/app/def']} path={pathHandler('/docs/app/def')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/app/client']} path={pathHandler('/docs/app/client')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/app/start']} path={pathHandler('/docs/app/start')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/app/style']} path={pathHandler('/docs/app/style')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/src/pages']} path={pathHandler('/docs/src/pages')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/src/layouts']} path={pathHandler('/docs/src/layouts')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/src/middleware']} path={pathHandler('/docs/src/middleware')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/src/components']} path={pathHandler('/docs/src/components')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/src/assets']} path={pathHandler('/docs/src/assets')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/src/styles']} path={pathHandler('/docs/src/styles')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/tools/hooks']} path={pathHandler('/docs/tools/hooks')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/tools/components']} path={pathHandler('/docs/tools/components')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/third-party/preact']} path={pathHandler('/docs/third-party/preact')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/third-party/express']} path={pathHandler('/docs/third-party/express')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/third-party/vite']} path={pathHandler('/docs/third-party/vite')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/third-party/typescript']} path={pathHandler('/docs/third-party/typescript')} component={_Navbar_Docs}/>
        <Route pages={pages} page={pages['/docs/third-party/eslint']} path={pathHandler('/docs/third-party/eslint')} component={_Navbar_Docs}/>
      </Router>
    </Layout_Navbar>
  )
}

function _Profile() {
  return (
    <Layout_Profile>
      <Router>
        <Route pages={pages} page={pages['/profile/:id']} path={pathHandler('/profile/:id')} component={Page_profile___x__id}/>
      </Router>
    </Layout_Profile>
  )
}

function _Navbar_Profile() {
  return (
    <Layout_Profile>
      <Router>
        <Route pages={pages} page={pages['/profile']} path={pathHandler('/profile')} component={Page_profile}/>
      </Router>
    </Layout_Profile>
  )
}

function _Navbar_Docs() {
  return (
    <Layout_Docs>
      <Router>
        <Route pages={pages} page={pages['/docs']} path={pathHandler('/docs')} component={Page_docs}/>
        <Route pages={pages} page={pages['/docs/app/def']} path={pathHandler('/docs/app/def')} component={Page_docs_app_def}/>
        <Route pages={pages} page={pages['/docs/app/client']} path={pathHandler('/docs/app/client')} component={Page_docs_app_client}/>
        <Route pages={pages} page={pages['/docs/app/start']} path={pathHandler('/docs/app/start')} component={Page_docs_app_start}/>
        <Route pages={pages} page={pages['/docs/app/style']} path={pathHandler('/docs/app/style')} component={Page_docs_app_style}/>
        <Route pages={pages} page={pages['/docs/src/pages']} path={pathHandler('/docs/src/pages')} component={Page_docs_src_pages}/>
        <Route pages={pages} page={pages['/docs/src/layouts']} path={pathHandler('/docs/src/layouts')} component={Page_docs_src_layouts}/>
        <Route pages={pages} page={pages['/docs/src/middleware']} path={pathHandler('/docs/src/middleware')} component={Page_docs_src_middleware}/>
        <Route pages={pages} page={pages['/docs/src/components']} path={pathHandler('/docs/src/components')} component={Page_docs_src_components}/>
        <Route pages={pages} page={pages['/docs/src/assets']} path={pathHandler('/docs/src/assets')} component={Page_docs_src_assets}/>
        <Route pages={pages} page={pages['/docs/src/styles']} path={pathHandler('/docs/src/styles')} component={Page_docs_src_styles}/>
        <Route pages={pages} page={pages['/docs/tools/hooks']} path={pathHandler('/docs/tools/hooks')} component={Page_docs_tools_hooks}/>
        <Route pages={pages} page={pages['/docs/tools/components']} path={pathHandler('/docs/tools/components')} component={Page_docs_tools_components}/>
        <Route pages={pages} page={pages['/docs/third-party/preact']} path={pathHandler('/docs/third-party/preact')} component={Page_docs_third__d__party_preact}/>
        <Route pages={pages} page={pages['/docs/third-party/express']} path={pathHandler('/docs/third-party/express')} component={Page_docs_third__d__party_express}/>
        <Route pages={pages} page={pages['/docs/third-party/vite']} path={pathHandler('/docs/third-party/vite')} component={Page_docs_third__d__party_vite}/>
        <Route pages={pages} page={pages['/docs/third-party/typescript']} path={pathHandler('/docs/third-party/typescript')} component={Page_docs_third__d__party_typescript}/>
        <Route pages={pages} page={pages['/docs/third-party/eslint']} path={pathHandler('/docs/third-party/eslint')} component={Page_docs_third__d__party_eslint}/>
      </Router>
    </Layout_Docs>
  )
}

if (typeof window !== 'undefined') {
  render(<Client/>, document.getElementById('app') as HTMLElement)
}
